/**
 * @fileoverview gRPC-Web generated client stub for rostovvpnrpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.1
// source: extension.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var base_pb = require('./base_pb.js')
const proto = {};
proto.rostovvpnrpc = require('./extension_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rostovvpnrpc.ExtensionHostServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rostovvpnrpc.ExtensionHostServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rostovvpnrpc.Empty,
 *   !proto.rostovvpnrpc.ExtensionList>}
 */
const methodDescriptor_ExtensionHostService_ListExtensions = new grpc.web.MethodDescriptor(
  '/rostovvpnrpc.ExtensionHostService/ListExtensions',
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.rostovvpnrpc.ExtensionList,
  /**
   * @param {!proto.rostovvpnrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rostovvpnrpc.ExtensionList.deserializeBinary
);


/**
 * @param {!proto.rostovvpnrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rostovvpnrpc.ExtensionList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rostovvpnrpc.ExtensionList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rostovvpnrpc.ExtensionHostServiceClient.prototype.listExtensions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rostovvpnrpc.ExtensionHostService/ListExtensions',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_ListExtensions,
      callback);
};


/**
 * @param {!proto.rostovvpnrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rostovvpnrpc.ExtensionList>}
 *     Promise that resolves to the response
 */
proto.rostovvpnrpc.ExtensionHostServicePromiseClient.prototype.listExtensions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rostovvpnrpc.ExtensionHostService/ListExtensions',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_ListExtensions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rostovvpnrpc.ExtensionRequest,
 *   !proto.rostovvpnrpc.ExtensionResponse>}
 */
const methodDescriptor_ExtensionHostService_Connect = new grpc.web.MethodDescriptor(
  '/rostovvpnrpc.ExtensionHostService/Connect',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.rostovvpnrpc.ExtensionRequest,
  proto.rostovvpnrpc.ExtensionResponse,
  /**
   * @param {!proto.rostovvpnrpc.ExtensionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rostovvpnrpc.ExtensionResponse.deserializeBinary
);


/**
 * @param {!proto.rostovvpnrpc.ExtensionRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.rostovvpnrpc.ExtensionResponse>}
 *     The XHR Node Readable Stream
 */
proto.rostovvpnrpc.ExtensionHostServiceClient.prototype.connect =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/rostovvpnrpc.ExtensionHostService/Connect',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_Connect);
};


/**
 * @param {!proto.rostovvpnrpc.ExtensionRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.rostovvpnrpc.ExtensionResponse>}
 *     The XHR Node Readable Stream
 */
proto.rostovvpnrpc.ExtensionHostServicePromiseClient.prototype.connect =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/rostovvpnrpc.ExtensionHostService/Connect',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_Connect);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rostovvpnrpc.EditExtensionRequest,
 *   !proto.rostovvpnrpc.ExtensionActionResult>}
 */
const methodDescriptor_ExtensionHostService_EditExtension = new grpc.web.MethodDescriptor(
  '/rostovvpnrpc.ExtensionHostService/EditExtension',
  grpc.web.MethodType.UNARY,
  proto.rostovvpnrpc.EditExtensionRequest,
  proto.rostovvpnrpc.ExtensionActionResult,
  /**
   * @param {!proto.rostovvpnrpc.EditExtensionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rostovvpnrpc.ExtensionActionResult.deserializeBinary
);


/**
 * @param {!proto.rostovvpnrpc.EditExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rostovvpnrpc.ExtensionActionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rostovvpnrpc.ExtensionActionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rostovvpnrpc.ExtensionHostServiceClient.prototype.editExtension =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rostovvpnrpc.ExtensionHostService/EditExtension',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_EditExtension,
      callback);
};


/**
 * @param {!proto.rostovvpnrpc.EditExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rostovvpnrpc.ExtensionActionResult>}
 *     Promise that resolves to the response
 */
proto.rostovvpnrpc.ExtensionHostServicePromiseClient.prototype.editExtension =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rostovvpnrpc.ExtensionHostService/EditExtension',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_EditExtension);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rostovvpnrpc.SendExtensionDataRequest,
 *   !proto.rostovvpnrpc.ExtensionActionResult>}
 */
const methodDescriptor_ExtensionHostService_SubmitForm = new grpc.web.MethodDescriptor(
  '/rostovvpnrpc.ExtensionHostService/SubmitForm',
  grpc.web.MethodType.UNARY,
  proto.rostovvpnrpc.SendExtensionDataRequest,
  proto.rostovvpnrpc.ExtensionActionResult,
  /**
   * @param {!proto.rostovvpnrpc.SendExtensionDataRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rostovvpnrpc.ExtensionActionResult.deserializeBinary
);


/**
 * @param {!proto.rostovvpnrpc.SendExtensionDataRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rostovvpnrpc.ExtensionActionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rostovvpnrpc.ExtensionActionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rostovvpnrpc.ExtensionHostServiceClient.prototype.submitForm =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rostovvpnrpc.ExtensionHostService/SubmitForm',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_SubmitForm,
      callback);
};


/**
 * @param {!proto.rostovvpnrpc.SendExtensionDataRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rostovvpnrpc.ExtensionActionResult>}
 *     Promise that resolves to the response
 */
proto.rostovvpnrpc.ExtensionHostServicePromiseClient.prototype.submitForm =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rostovvpnrpc.ExtensionHostService/SubmitForm',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_SubmitForm);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rostovvpnrpc.ExtensionRequest,
 *   !proto.rostovvpnrpc.ExtensionActionResult>}
 */
const methodDescriptor_ExtensionHostService_Close = new grpc.web.MethodDescriptor(
  '/rostovvpnrpc.ExtensionHostService/Close',
  grpc.web.MethodType.UNARY,
  proto.rostovvpnrpc.ExtensionRequest,
  proto.rostovvpnrpc.ExtensionActionResult,
  /**
   * @param {!proto.rostovvpnrpc.ExtensionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rostovvpnrpc.ExtensionActionResult.deserializeBinary
);


/**
 * @param {!proto.rostovvpnrpc.ExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rostovvpnrpc.ExtensionActionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rostovvpnrpc.ExtensionActionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rostovvpnrpc.ExtensionHostServiceClient.prototype.close =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rostovvpnrpc.ExtensionHostService/Close',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_Close,
      callback);
};


/**
 * @param {!proto.rostovvpnrpc.ExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rostovvpnrpc.ExtensionActionResult>}
 *     Promise that resolves to the response
 */
proto.rostovvpnrpc.ExtensionHostServicePromiseClient.prototype.close =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rostovvpnrpc.ExtensionHostService/Close',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_Close);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rostovvpnrpc.ExtensionRequest,
 *   !proto.rostovvpnrpc.ExtensionActionResult>}
 */
const methodDescriptor_ExtensionHostService_GetUI = new grpc.web.MethodDescriptor(
  '/rostovvpnrpc.ExtensionHostService/GetUI',
  grpc.web.MethodType.UNARY,
  proto.rostovvpnrpc.ExtensionRequest,
  proto.rostovvpnrpc.ExtensionActionResult,
  /**
   * @param {!proto.rostovvpnrpc.ExtensionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rostovvpnrpc.ExtensionActionResult.deserializeBinary
);


/**
 * @param {!proto.rostovvpnrpc.ExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rostovvpnrpc.ExtensionActionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rostovvpnrpc.ExtensionActionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rostovvpnrpc.ExtensionHostServiceClient.prototype.getUI =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rostovvpnrpc.ExtensionHostService/GetUI',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_GetUI,
      callback);
};


/**
 * @param {!proto.rostovvpnrpc.ExtensionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rostovvpnrpc.ExtensionActionResult>}
 *     Promise that resolves to the response
 */
proto.rostovvpnrpc.ExtensionHostServicePromiseClient.prototype.getUI =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rostovvpnrpc.ExtensionHostService/GetUI',
      request,
      metadata || {},
      methodDescriptor_ExtensionHostService_GetUI);
};


module.exports = proto.rostovvpnrpc;

