version: '3.8'

services:
  rostovvpn:
    image: ghcr.io/Darkmen203/rostovvpn-core:latest
    network_mode: host
    environment:
      CONFIG: "https://github.com/Darkmen203/RostovVPN/raw/refs/heads/main/test.configs/warp"
    volumes:
      - ./rostovvpn.json:/rostovvpn/rostovvpn.json
    command: ["/opt/rostovvpn.sh"]
